document.getElementById('gameInfo1').innerText = "Humanity's last safe city has fallen to an overwhelming invasion force, led by Ghaul, the imposing commander of the brutal Red Legion. He has stripped the city's Guardians of their power, and forced the survivors to flee. You will venture to mysterious, unexplored worlds of our solar system to discover an arsenal of weapons and devastating new combat abilities. To defeat the Red Legion and confront Ghaul, you must reunite humanity's scattered heroes, stand together, and fight back to reclaim our home.";

document.getElementById('gameInfo2').innerText = "Raise your fists and get ready for the ultimate battle on the next generation of home consoles. Powered by the Unreal Engine 4, the storied fighting franchise returns for another round in Tekken 7. With the faithful 3D battle system and gameplay intact, Tekken 7 takes the franchise to the next level with photo-realistic graphics and new and innovative features and fighting mechanics. Tekken 7 resurrects the attitude, competitiveness and showmanship rooted in its arcade DNA to provide the ultimate fighting game experience.";

document.getElementById('gameInfo3').innerText = "New characters and a new battle mode, plus 1080p resolution, make this a 'deluxe' version of the game that came out for Wii U in 2015. Easily my favorite Mario Kart game, I'm excited to play the new battle mode with Splatoon characters. I do wish that there were new tracks, or a Mario Kart 9 was in the offing, though.";

document.getElementById('gameInfo4').innerText = "Take on the role of skilled hunter Aloy as you explore a vibrant and lush world inhabited by mysterious mechanized creatures. Embark on a compelling, emotional journey and unravel mysteries of tribal societies, ancient artifacts and advanced technologies that will determine the fate of this planet, and of life itself.";

document.getElementById('gameInfo5').innerText = " The premiere DC Comics fighting game returns to modern consoles with bigger and better graphics and a whole bunch of superheroes and villains to choose from. Should be fun.";
